<?php
namespace Tests\Feature;
use CodeIgniter\Test\CIUnitTestCase;
use CodeIgniter\Test\FeatureTestTrait;
use CodeIgniter\Test\DatabaseTestTrait;
class ApplicationTest extends CIUnitTestCase {
 use FeatureTestTrait,DatabaseTestTrait; protected $migrate=true; protected $refresh=true; protected $seed='Tests\\Support\\Database\\Seeds\\TestSeeder'; protected $namespace='App';
 public function testPublicPagesAndHealth():void{foreach(['/','/about','/login'] as $url)$this->get($url)->assertStatus(200);$result=$this->get('/health');$result->assertStatus(200);$result->assertJSONFragment(['status'=>'ok']);}
 public function testProtectedRoutesRedirectGuests():void{$this->get('/customers')->assertRedirectTo('/login');$this->get('/users')->assertRedirectTo('/login');}
 public function testLoginFailureAndSuccess():void{$this->post('/login',['username'=>'admin','password'=>'wrong'])->assertRedirect();$result=$this->post('/login',['username'=>'admin','password'=>'ValidTest!123']);$result->assertRedirectTo('/customers');}
 public function testAuthenticatedListsAndLogout():void{$session=['authenticated'=>true,'user_id'=>1,'username'=>'admin','role'=>'admin'];$this->withSession($session)->get('/customers')->assertSee('Test Customer');$this->withSession($session)->get('/users')->assertSee('Test Admin');$this->withSession($session)->post('/logout')->assertRedirectTo('/login');}
 public function testCustomerValidationCreateUpdateAndMissing():void{$session=['authenticated'=>true,'user_id'=>1,'username'=>'admin','role'=>'admin'];$this->withSession($session)->post('/customers',['full_name'=>'','email'=>'bad'])->assertRedirect();$this->withSession($session)->post('/customers',['full_name'=>'New Customer','email'=>'new@example.test','phone'=>''])->assertRedirectTo('/customers');$id=db_connect()->table('customers')->where('email','new@example.test')->get()->getRow()->id;$this->withSession($session)->post('/customers/'.$id,['full_name'=>'Updated Customer','email'=>'invalid'])->assertRedirect();$this->withSession($session)->post('/customers/'.$id,['full_name'=>'Updated Customer','email'=>'updated@example.test','phone'=>'555'])->assertRedirectTo('/customers');$this->withSession($session)->get('/customers/999999/edit')->assertStatus(404);}
 public function testUserRulesHashingAndPasswordPreservation():void{$s=['authenticated'=>true,'user_id'=>1,'username'=>'admin','role'=>'admin'];$this->withSession($s)->post('/users',['username'=>'admin','full_name'=>'Duplicate','role'=>'cashier','password'=>'LongPassword!1'])->assertRedirect();$this->withSession($s)->post('/users',['username'=>'new.user','full_name'=>'New User','role'=>'cashier','password'=>'LongPassword!1'])->assertRedirectTo('/users');$user=db_connect()->table('users')->where('username','new.user')->get()->getRowArray();$this->assertTrue(password_verify('LongPassword!1',$user['password']));$hash=$user['password'];$this->withSession($s)->post('/users/'.$user['id'],['username'=>'new.user','full_name'=>'Updated User','role'=>'manager','password'=>''])->assertRedirectTo('/users');$updated=db_connect()->table('users')->where('id',$user['id'])->get()->getRowArray();$this->assertSame($hash,$updated['password']);$this->withSession($s)->get('/users/999999/edit')->assertStatus(404);}
 public function testAvatarServiceAcceptsImageAndRejectsInvalidAndOversizeFiles():void{$dir=sys_get_temp_dir().DIRECTORY_SEPARATOR.'counterpoint-avatar-'.bin2hex(random_bytes(5));mkdir($dir);putenv('AVATAR_UPLOAD_PATH='.$dir);$_ENV['AVATAR_UPLOAD_PATH']=$dir;$png=$dir.DIRECTORY_SEPARATOR.'source.png';$image=imagecreatetruecolor(20,20);imagepng($image,$png);imagedestroy($image);$service=new \App\Libraries\AvatarService();$saved=$service->save(new \CodeIgniter\HTTP\Files\UploadedFile($png,'avatar.png','image/png',UPLOAD_ERR_OK,true));$this->assertMatchesRegularExpression('/^[a-f0-9]{48}\.png$/',$saved);$this->assertFileExists($dir.DIRECTORY_SEPARATOR.$saved);$text=$dir.DIRECTORY_SEPARATOR.'bad.jpg';file_put_contents($text,'not an image');$this->expectException(\RuntimeException::class);try{$service->save(new \CodeIgniter\HTTP\Files\UploadedFile($text,'bad.jpg','image/jpeg',UPLOAD_ERR_OK,true));}finally{$service->delete($saved);@unlink($png);@unlink($text);@rmdir($dir);}}
 public function testAvatarServiceRejectsOversizeFile():void{$dir=sys_get_temp_dir().DIRECTORY_SEPARATOR.'counterpoint-large-'.bin2hex(random_bytes(5));mkdir($dir);putenv('AVATAR_UPLOAD_PATH='.$dir);$_ENV['AVATAR_UPLOAD_PATH']=$dir;$path=$dir.DIRECTORY_SEPARATOR.'large.png';$handle=fopen($path,'wb');fseek($handle,2097152);fwrite($handle,"0");fclose($handle);$this->expectException(\RuntimeException::class);try{(new \App\Libraries\AvatarService())->save(new \CodeIgniter\HTTP\Files\UploadedFile($path,'large.png','image/png',UPLOAD_ERR_OK,true));}finally{@unlink($path);@rmdir($dir);}}
}
